name: Publish

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  publish-demo:
    runs-on: ubuntu-latest
    name: Publish Demo Image

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Demo Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            PUBLIC_API_URL=https://demo-api.letsrevel.io
            ORIGIN=https://demo.letsrevel.io
            PUBLIC_VERSION=${{ github.event.release.tag_name }}
          tags: |
            ghcr.io/letsrevel/revel-frontend:latest-demo
            ghcr.io/letsrevel/revel-frontend:${{ github.event.release.tag_name }}-demo
          cache-from: type=gha,scope=demo
          cache-to: type=gha,mode=max,scope=demo

  publish-prod:
    runs-on: ubuntu-latest
    name: Publish Production Image

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Production Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            PUBLIC_API_URL=https://api.letsrevel.io
            ORIGIN=https://letsrevel.io
            PUBLIC_VERSION=${{ github.event.release.tag_name }}
          tags: |
            ghcr.io/letsrevel/revel-frontend:latest
            ghcr.io/letsrevel/revel-frontend:${{ github.event.release.tag_name }}
          cache-from: type=gha,scope=prod
          cache-to: type=gha,mode=max,scope=prod
